### ISSUE TITLE
Dead prj

### ISSUE THREAD

**Issue by blondie63** [JLiao98/IoT-Manager#10]
Hi, is this prj dead ?
All demo link does'nt works..

**Comment by raksdewji** [comment]
Hey thanks for checking out the project. Sorry about that, we developed this for a school project but it hasn't been maintained since. Are you trying to demo the android app? I uploaded the APK to the GitHub release as well so you can download it [here](https://github.com/JLiao98/IoT-Manager/releases).

**Comment by blondie63** [comment]
Hi, thanks for your answer..
I've tried apk but i've seen thats i need other demo
Thanks the same, regards
